### ISSUE TITLE
TypeError 'company_id' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by denever** [jazzband/django-simple-history#1]
I get this error here:

```
def create_historical_record(self, instance, type):
...
    manager.create(history_type=type, changed_by=changed_by, **attrs)
....
```

My Model is:

```
class Department(models.Model):
    company = models.ForeignKey(Company, verbose_name=_('Company'))
    name = models.CharField(_('Department name'), max_length=200)
    description = models.TextField(_('Department description'))
    size = models.PositiveIntegerField('Department size mq.')

    history = HistoricalRecords()
```

Where am I wrong?

Thank you

**Comment by kazgm** [comment]
Products.objects.create(title="New product 2", descriptions="another one", price="12300", summary="sweet")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\kazgm\Dev\kazhome\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kazgm\Dev\kazhome\lib\site-packages\django\db\models\query.py", line 415, in create
    obj = self.model(**kwargs)
  File "C:\Users\kazgm\Dev\kazhome\lib\site-packages\django\db\models\base.py", line 495, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'title' is an invalid keyword argument for this function
Pls i need help on this error.

**Comment by macro1** [comment]
@kazgm: I don't see simple_history anywhere in your traceback. I don't think your issue has anything to do with this library.
Here is the Django documentation for create:
https://docs.djangoproject.com/en/2.2/ref/models/querysets/#create
