### ISSUE TITLE
Disable history_change_reason field when migrating from old version

### ISSUE THREAD

**Issue by matejsp** [jazzband/django-simple-history#1003]
**Problem Statement**
We have a lot of tables in production some of which are very large and we want to migrate to newer version of django-simple-history. There was new field added named history_change_reason and this is making migration very costly for large tables.

**Describe the solution you'd like**
Setting to disable saving of history_change_reason field globally and/or per table (couple of huuuge tables)

**Describe alternatives you've considered**
Patching the library to not save the field. We can prepare a patch to enable/disable this field if it  would be interesting for this project.
SIMPLE_HISTORY_HISTORY_CHANGE_REASON_ENABLED = True (default)
history_change_reason_field_enabled=True (default) as HistoricalRecords constructor parameter

**Comment by ddabble** [comment]
I'm guessing this is no longer generally an issue, considering that `history_change_reason` has been around for a few years now, so closing 😅

**Comment by matejsp** [comment]
Correct. With migration to Mysql 8.x that supports instant algorithm for adding columns we solved this issue.
