### ISSUE TITLE
How to add actions in the admin integration, similar to django default history view

### ISSUE THREAD

**Issue by zilehuda** [jazzband/django-simple-history#1030]
**Problem Statement**
I have changed the is_active column from True to False, now when I look at the history view from admin integration, I am not able to see which field has been changed, but in the default django history list, it shows changes in the action column. How can I do this in the django-simple-history?

In short, I wanted to know, what has been changes by looking at the list display

**Comment by PetrDlouhy** [comment]
@zilehuda If I do get this right, this is solved in PR #1128. It would start displaying column "History diff" like this:
![Snímek obrazovky_2023-09-11_12-35-02](https://github.com/jazzband/django-simple-history/assets/156755/b094bbcc-24fd-47a8-b645-594a54f904a0)

**Comment by ddabble** [comment]
I'm assuming that the PR @PetrDlouhy linked solves this issue, so I'm linking it :)
