### ISSUE TITLE
3.1.1 generates migrations even flag SIMPLE_HISTORY_DATE_INDEX has false value

### ISSUE THREAD

**Issue by awais786** [jazzband/django-simple-history#1034]
I am trying to upgrade a project to 3.1.1 and I have set `SIMPLE_HISTORY_DATE_INDEX=False`. Idealy it should not generate any new migration but it is making few. Although migration does not have any index change but lots of ordering changes.

**To Reproduce**
1. Install 3.1.1.
2. set SIMPLE_HISTORY_DATE_INDEX=False
3. Run make migrations.

**Expected behavior**
It should not generate any new migration.

**Actual behavior**
It generates a migration. Although there is no index change but it is adding many changes in lots of tables.
```
 migrations.AlterModelOptions(
            name='historicalcourse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course', 'verbose_name_plural': 'historical courses'},
        ),
```

**Comment by ddabble** [comment]
Those model option changes in your migrations are unfortunately unavoidable, as there have not been implemented any settings to disable them. The `SIMPLE_HISTORY_DATE_INDEX` setting is unrelated, and instead controls how the `history_date` field is indexed.

Closing, as potentially requesting implementing settings to disable the mentioned model options, seems out of scope for this issue. Please reopen if you disagree 🙂
