### ISSUE TITLE
v3.2.0 missing from PyPi

### ISSUE THREAD

**Issue by Kangaroux** [jazzband/django-simple-history#1045]
```
$ pip install django-simple-history==3.2.0
ERROR: Could not find a version that satisfies the requirement django-simple-history==3.2.0 (from versions: 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1rc1, 1.9.1, 2.0, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.9.0, 2.10.0, 2.11.0, 2.12.0, 3.0.0, 3.1.1)
ERROR: No matching distribution found for django-simple-history==3.2.0
```

**Comment by michaeljaszczuk** [comment]
You can also use simple:
`pip install git+https://github.com/jazzband/django-simple-history.git@3.2.0`

**Comment by tim-schilling** [comment]
@jezdez would you be able to release this package to PyPI from jazzband? Also, I think this project could use another project lead. I never got up to speed on the project enough to take it over. Maybe @jeking3 if he's willing / available?

**Comment by liviocunha** [comment]
Do you have a forecast when it launches on Pypi?

**Comment by treyhunner** [comment]
I just pushed the `whl` and `tar.gz` to PyPI for 3.2.0.

I agree with @tim-schilling that the project could use another lead. 👍
