### ISSUE TITLE
Wrong documentation reference - many_to_many is really m2m_fields

### ISSUE THREAD

**Issue by michaeljaszczuk** [jazzband/django-simple-history#1049]
**Describe the bug**
In docs page https://django-simple-history.readthedocs.io/en/3.2.0/historical_model.html#tracking-many-to-many-relationships 
there is example with many_to_many argument, however in the 3.2.0 version, it's called m2m_fields

**Expected behavior**
Update documentation and use m2m_fields as arg name

**Screenshots**
<img width="1362" alt="Screenshot 2022-10-21 at 04 25 49" src="https://user-images.githubusercontent.com/38879663/197149613-a21cc83b-9715-49c3-a1ad-caf94c11de39.png">

**Comment by legau** [comment]
Resolved in #1042

**Comment by ddabble** [comment]
Closing, as it was resolved in the PR mentioned by @legau
