### ISSUE TITLE
Change m2m_fields to accept a list of field names as strings

### ISSUE THREAD

**Issue by Kangaroux** [jazzband/django-simple-history#1057]
`m2m_fields` requires that you pass it a field instance, whereas the other params allow passing in the field name as a string. Other than being inconsistent, this also means that the `history` attribute can't be set at the top of the model (because `m2m_fields` references a field which has not yet been defined). In our project we like to have it at the top of the model definition because it makes it obvious which models have history support.

**Comment by antoineauger** [comment]
@Kangaroux That would be really great...

FYI, I asked if someone had more info [here](https://github.com/jazzband/django-simple-history/issues/1079#issuecomment-1444065532).

**Comment by ddabble** [comment]
Seems like this is resolved by #1243.
