### ISSUE TITLE
Suspicous Wheel Update for versions 3.1.x on PyPI

### ISSUE THREAD

**Issue by filipweidemann** [jazzband/django-simple-history#1065]
Good evening!

During a recent build of one of our projects, we discovered that the Wheels of all `3.1.x` versions of `django-simple-history` were updated on PyPI. This happened on **December 2nd between ~16:27 & 16:28**. We did see this inside the PyPI JSON output of the repository (https://pypi.org/pypi/django-simple-history/json)

As expected, this **breaks the installation because of mismatching hashes.** 

We did a quick check and didn't see any relevant code changes. There was some activity on friday regarding arabic translations and some dependabot bumps, but neither of those triggered an obvious release inside GitHub Actions, therefore we are unable to verify if this is an intentional or potentially malicious update of the wheels, since we lack the proper papertrail for this change.

Sorry for jumping in here without using a proper template, I couldn't decide which one to pick for this but I figured this **_might_** be interesting for a lot of people, and I would really appreciate if someone could clarify this with a few quick words so that anyone facing the same questions can find a response in here!

Thank you so much and best regards!

**Comment by rossmechanic** [comment]
Thanks for raising @filipweidemann. That was me. Hadn't check in here in a while and looked at Jazzband portion of the repo which said the 3.1.0 release never happened (so I released that) and Jazzband said the 3.1.1 wheel release never happened so I updated that as well. Assuming one of the other maintainers had been doing releases while I was MIA and just missed those.

**Comment by filipweidemann** [comment]
Thanks @rossmechanic! This eases my mind :)

I consider this closed now!
