### ISSUE TITLE
clean_duplicate_history ignores excluded_fields in models declaration

### ISSUE THREAD

**Issue by sambot83** [jazzband/django-simple-history#1138]
If your model uses:
history = HistoricalRecords(
        excluded_fields=["myfield"]
    )

calling clean_duplicate_history will ending by an error: 
simple_history/models.py", line 890, in diff_against
    old_value = old_values[field]
KeyError: 'myfield'

why because in diff_against() :
included_fields = {
                f.name for f in old_history.instance_type._meta.fields if f.editable
} ignores excluded_fields in the models declaration.

**Comment by ddabble** [comment]
Thanks for the report! This has already been fixed by #1038, but the changes have not yet been released. I'll try creating a new release 🙂

**Comment by ddabble** [comment]
Release 3.3.0 has now been uploaded to the Jazzband website, and we should only have to wait for one of the project leads or roadies to release it to PyPI 🙂 (see https://jazzband.co/about/releases)
