### ISSUE TITLE
Is there a recommended way to version a *model graph*

### ISSUE THREAD

**Issue by estebistec** [jazzband/django-simple-history#118]
I _think_ this is what #17 is getting at, but I thought it was worth asking to be clear.

When models have FK relations, you can put history on both models, but the FK references on history instances will still always point to the primary, non-history objects.

So, e.g.,
- I have model `A` and model `B` with an FK to `A`
- For an instance of `A` with several related instances of `B`
- Where the instances of `B` are being changed

What is the best way to have multiple versions of the `A` instance that is related to the correct historical instances of `B`?

I see that the history manager has `as_of`, which takes a date-time, but that is of course potentially non-exact if two versions could ever land on the same measurable instant.

Is there a better or more obvious way I'm not seeing? Is there a way to link historical versions of one model to historical versions of another to get _model graph_ snapshots?

**Comment by matheusjardimb** [comment]
I'm not sure if I'm asking the same thing as the stated in the question, but this is my situation:

```
class Product(Model):
    history = HistoricalRecords()
    name = CharField(max_length=200, verbose_name=_('name'))

class Order(Model):
    history = HistoricalRecords()
    company = ForeignKey('Company', verbose_name=_('company'), on_delete=PROTECT)
    customer = ForeignKey('Customer', verbose_name=_('customer'), on_delete=PROTECT)
    purchased_at = DateTimeField(verbose_name=_('purchased at'), null=True, blank=True)

class OrderItem(DateModel):
    history = HistoricalRecords()
    order = ForeignKey('Order', verbose_name=_('order'), on_delete=PROTECT)
    product = ForeignKey('Product', verbose_name=_('product'), on_delete=SET_NULL)
    quantity = PositiveIntegerField(verbose_name=_('quantity'), default=1)
```

The store admin may change the product name over time (or even delete it) but I need to show to the customer the information exactly as when he bought it.

By using the code below, I'm able to get only the historic version of Order, but OrderItem and Product data retrieved are not the historical ones.
```
order = Order.objects.first()
as_bought = order.history.as_of(order.order_created_at)
```

Let me know if this post is not related, so that I can create a new issue.

Thanks!

**Comment by adibo** [comment]
I came across a similar use case and agree that it would be great to have a version of `as_of` which produces a historical snapshot of the model instance itself (which it does) with historical versions of all related models. I don't think it is possible today (or trivial to implement).
I guess, for now, you should be able to live with something like:

```
order_items = OrderItem.objects.filter(order_id=as_bought.id) 
historic_items = [item.history.as_of(order.order_created_at) for item in order_items]
```

Having items, you can go for historical versions of related products:

```
item.product.history.as_of(order.order_created_at)
```

I have not tested the code, but you get the idea. Hope it helps.

**Comment by browze** [comment]
Just wanted to add my +1 - this would be a great feature - I'm quite surprised there hasn't been more clamour for it!  As I'm really pushed for time right now I've just manually queried for historic related sets and stitched them together in python - but asof_related would be great.
