### ISSUE TITLE
Add Pagination and Filtering

### ISSUE THREAD

**Issue by RumitAP** [jazzband/django-simple-history#1219]
**Problem Statement**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RumitAP** [comment]
I have a fix but it wont allow me to push the code up 

git push --set-upstream origin pagination-and-filtering
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
remote: Permission to jazzband/django-simple-history.git denied to RumitAP.
fatal: unable to access 'https://github.com/jazzband/django-simple-history.git/': The requested URL returned error: 403

**Comment by ddabble** [comment]
@RumitAP Just create a fork of this repo, push to a branch there, and open a PR in this repo 🙂
