### ISSUE TITLE
Django-simple-history v3.3.0 is reporting DeprecationWarning: pkg_resources is deprecated as an API with Django v3.2.

### ISSUE THREAD

**Issue by bschollnick** [jazzband/django-simple-history#1238]
**Describe the bug**
Django-simple-history v3.3.0 is reporting DeprecationWarning: pkg_resources is deprecated as an API with Django v3.2.

../.venv/lib/python3.9/site-packages/simple_history/__init__.py:1
  /work/site1/.venv/lib/python3.9/site-packages/simple_history/__init__.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import DistributionNotFound, get_distribution

We were on v3.0, and have upgraded, to eliminate Django41 warnings, since we are working to upgrade to Django v4.1.

Please note, I am seeing a v3.4 in the releases list, but pypi isn't showing that version as released?

**To Reproduce**
1) pip install django-simple-history
2) run our test pytest suite

**Expected behavior**
To not see Depreciation Warnings?

**Environment (please complete the following information):**
 - OS: Red Heat Enterprise 8
 - Python 3.9.16
 - Django 3.2.20
 - Django Simple History Version: 3.3.0
 - Database Version: "PostgreSQL 11.12 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit"

**Comment by ddabble** [comment]
Yes, this was resolved in v3.4.0, but that version has not yet been released to PyPI by the project leads. However, I just made [a request to the Jazzband roadies](https://github.com/jazzband/help/issues/344) to have it released, so I'm assuming it won't be long until it happens 🙂

**Comment by ddabble** [comment]
Please reopen if it turns out that your issue was not resolved after all 😊
