### ISSUE TITLE
3.4.0 is not on PyPI?

### ISSUE THREAD

**Issue by Tenzer** [jazzband/django-simple-history#1253]
**Describe the bug**
I can see version 3.4.0 has been tagged in this repository and `CHANGES.rst` lists the release date as 2023-08-18, but the release has not made it onto [PyPI](https://pypi.org/project/django-simple-history/#history). Is that deliberate or an oversight?

It would be ideal to have a way to install the latest version which doesn't require us to install it directly from the Git repository.

**To Reproduce**
1. Run `pip install django-simple-history`
2. Observe version 3.3.0 is installed, not 3.4.0

**Expected behavior**
Version 3.4.0 should be available on PyPI.

**Comment by ddabble** [comment]
The release is still awaiting publishing from the people with permissions to do so, see https://github.com/jazzband/django-simple-history/issues/1238#issuecomment-1696625980 and https://github.com/jazzband/help/issues/344. I'm not sure what else can be done 😕

I'll leave this issue open until the release has been published.

**Comment by treyhunner** [comment]
Version 3.4.0 is now on PyPI
