### ISSUE TITLE
Q: How do I create my model when it is not in the same database as User model?

### ISSUE THREAD

**Issue by Star-fly-Cheng** [jazzband/django-simple-history#1275]
`
class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    history = HistoricalRecords()`

_Poll_ is not in the same database as User model. When I run migrate, there is a error:
`django.db.utils.OperationalError: (1824, "Failed to open the referenced table 'auth_user'")`

How can I fix it? Thanks very much.

**Comment by ddabble** [comment]
@Star-fly-Cheng Did you close the issue by accident, or did you solve it on your own..?

In the former case, would you mind providing a more complete reproducible example? I personally don't have any experience using multiple databases, and so it would be easier for me to reproduce the issue if I had the relevant parts of your code related to that 🙂
