### ISSUE TITLE
Add support for custom history manager

### ISSUE THREAD

**Issue by Kangaroux** [jazzband/django-simple-history#1280]
**Problem Statement**
I have a model that makes heavy use of annotations. I want to be able to fetch the historical records for a model and have the annotations already included. In order to do this, I need to extend the history manager, but there's no straightforward way to actually inject it and use it.

**Describe the solution you'd like**
`HistoricalRecords` could accept an argument for the manager class. 

```python
from simple_history.manager import HistoryManager, HistoricalQuerySet

class MyModelHistoricalManager(HistoryManager):
  ...

class MyModel:
  history = HistoricalRecords(manager_cls=MyModelHistoricalManager)
  # or even better
  history = HistoricalRecords(manager_cls=MyModelHistoricalManager.from_queryset(HistoricalQuerySet))
```

**Comment by tim-schilling** [comment]
@Kangaroux I think I have a solution for you in #1306

**Comment by aprams** [comment]
@tim-schilling love the change, thanks!
