### ISSUE TITLE
Changing many-to-many field creates additional HistoricalRecord

### ISSUE THREAD

**Issue by VeraBoersma** [jazzband/django-simple-history#1313]
**Describe the bug**
When updating or creating a model with a many-to-many field (after specifying the m2m_fields), two historical records get created. One with the change to the many-to-many field, and one with the change to any other field.
One of the records is created after updating, but before saving the model and holds the information of the change to the m2m related field. The second record is created after saving, holding the information of the change to the regular fields.

**To Reproduce**
Have two models with a many-to-many relation
Create an instance of both.
Check the length of the history.all() for the entries.
Update but do not save the m2m field of the instance holding the m2m field (optional; also update a non-related field) and check the length (and content) of the history.all().
Save the entry and check the length (and content) of the history.all().

**Expected behavior**
Only a single historical record being created recording both the m2m field and other field changes

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Django Simple History Version: 3.4.0
 - Django Version: 4.2.10
 - Database Version: sqlite3 3.40.1

**Comment by VeraBoersma** [comment]
To clarify, we intend to use django-simple-history in a database which has a user interface, using the generic create and update views from Django, which I think causes the issue, as that one might have the different .add() and .save() actions in there causing the duplicate records.

We have now locally managed to fix it by removing duplicate history records (based on user and timestamp (to the second) before parsing them.

In case anyone is interested:

```python
    def remove_duplicate_records(self, object_history: HistoricalRecords) -> List[HistoricalChanges]:
        """
        Removes duplicate history records based on user and timestamp.
        This is to accommodate for that when changing m2m fields, django-simple-history creates 2 historical records.
        One when the update is made and one when the change is made.
        Only the first in the list of each set of duplicated entries needs to be kept, as that holds all the changes.
        :param object_history: HistoricalRecords: List of historical records for an object containing potential
                               duplicates
        :return: List[HistoricalChanges]: Deduplicated list of historical records for the object.
        """
        deduplicated_records = [object_history[0]]  # initiate with the latest change as first entry
        for i in range(len(object_history) - 1):
            previous_record = object_history[i]
            current_record = object_history[i + 1]
            previous_timestamp = previous_record.history_date.strftime('%Y-%m-%d %H:%M:%S')
            current_timestamp = current_record.history_date.strftime('%Y-%m-%d %H:%M:%S')
            # When the current record differs from the previous one on user and timestamp, add it to deduplicated
            if current_record.history_user != previous_record.history_user or current_timestamp != previous_timestamp:
                deduplicated_records.append(current_record)
        return deduplicated_records

```

**Comment by ddabble** [comment]
I don't think it's a viable option fixing this (intended) behavior, unfortunately. This is because updating M2M fields necessarily changes a different table than the model's table - which happens in a separate transaction from updating the model's table (unless it's part of an atomic transaction, of course) - and since this library does not keep track of transactions, we have to create two historical records in these cases.

> Update but do not save the m2m field of the instance holding the m2m field

I'm assuming you're talking about calling the `add()`, `remove()` or `set()` M2M manager methods..? Because calling them will immediately change the M2M table, regardless of whether e.g. `save()` has been called on the model object, in case you weren't already aware 🙂

**Comment by ddabble** [comment]
Other than that, thank you for posting the code that solved your problem!

Please reopen if you'd like to discuss alternative solutions 🙂
