### ISSUE TITLE
Updating M2M relations causes unnecessary DB queries

### ISSUE THREAD

**Issue by alimony** [jazzband/django-simple-history#1317]
If I have the models e.g. `User` and `Group` where `Group` has an m2m field to `User` and also has a field like `history = HistoricalRecords(m2m_fields=[users])`, calling any of the m2m set update methods such as `group.users.set(users)` or `group.users.add(user1, user2)` causes duplicate queries.

I have an example of this where I add 25 users to a group, and it generates 25 extra user selects and 25 extra group selects.

Is there any way to work around this? Since I do this right after creating a new `Group`, I tried bypassing history saving on the `Group` model as suggested by the documentation, but related sets seem unaffected by this.

**Comment by ddabble** [comment]
I'm not sure I'm able to reproduce your issue 🤔 Calling e.g. `add()` with multiple arguments should only create one historical record (see e.g. [this test case](https://github.com/jazzband/django-simple-history/blob/3.5.0/simple_history/tests/tests/test_models.py#L2143-L2147))... Could you provide some (complete) test case code that reproduces your issue? 🙂

**Comment by alimony** [comment]
This is not about duplicate records, but duplicate database queries, as identified by e.g. Django Debug Toolbar. It’s a performance issue. Can you also see duplicate queries by inspecting with debug toolbar? If not, I’ll try and make a test case.

**Comment by ddabble** [comment]
Ah, sorry, I misread your description 😅 I'm able to reproduce it, and will open a PR for it :)

**Comment by alimony** [comment]
Thank you, lovely to hear! Let me know if I can help in any way.

**Comment by alimony** [comment]
Any update on this?

**Comment by ddabble** [comment]
I've made a fix for it locally, but considering that @tim-schilling and I are the only currently active maintainers, I want to focus on finishing #1128 first, which seems close to being merged 🙂

**Comment by alimony** [comment]
@ddabble Any idea when we might see this in a release?

**Comment by ddabble** [comment]
I'm planning on creating a new release after #1344 has been merged 🙂

**Comment by ddabble** [comment]
@alimony I've created a GitHub release for version 3.6.0, but it's yet to be published to PyPI; see progress in #1345
