### ISSUE TITLE
Remove the "not created" condition from post_save when skipping history creation

### ISSUE THREAD

**Issue by ailandini-accenture** [jazzband/django-simple-history#1327]
**Problem Statement**
When working with the library, it provides the options to _not_ create history if I set the self attribute _skip_history_when_saving_ to true in a given model's _save()_. However, if the _save()_ is the first instance of a record, it creates the history anyway. This seems obfuscated and counter-intuitive - as if I'm intentionally skipping the history creation, I would expect the history to not be created.

**Describe the solution you'd like**
Removal of the "not created" condition [in post_save](https://github.com/jazzband/django-simple-history/blob/master/simple_history/models.py#L654) 

**Describe alternatives you've considered**
In my case, I overwrote the post_save from my own class which inherited the HistoricalRecords and that works fine, but it feels like a strange solution to the problem statement.

**Comment by tim-schilling** [comment]
Duplicate of #1141
