### ISSUE TITLE
Add support for HistoricOneToOneField

### ISSUE THREAD

**Issue by JordanHyatt** [jazzband/django-simple-history#1389]
HistoricForeignKey is a very nice feature, it would be great to extend this support to OneToOneFields.

**Comment by kgeidel** [comment]
Yes, that would be swell. HistoricForeignKey(unique=True) throws that warning about using one to one. Would be nice to be able to have history on the 1-1 w/o needing to suppress that warning.

**Comment by ddabble** [comment]
Duplicate of #1031
