### ISSUE TITLE
Effect of django simple history on app performance.

### ISSUE THREAD

**Issue by Gauravwagh** [jazzband/django-simple-history#261]
Curious about the effect of django simple history on web app performance. Because for each action it creates one object wether it is create, update or delete.

**Comment by d1ffuz0r** [comment]
@Gauravwagh Generally you will not see major slowdowns. Except for mass updates, then it'll become noticeable. Solution that worked out  great for us is: we override `HistoricalRecords.create_historical_record` and calling celery task inside to store history without blocking operation

```python
@app.task(queue=HISTORY_QUEUE)
def save_history_record(app_name, model_name, manager_name, attrs, using):
    model = django_apps.get_model(app_name, model_name)
    history_manager = getattr(model, manager_name)
    history_record = history_manager.model(**attrs)
    history_record.save(using=using)
```

**Comment by Gauravwagh81** [comment]
> @Gauravwagh Generally you will not see major slowdowns. Except for mass updates, then it'll become noticeable. Solution that worked out great for us is: we override `HistoricalRecords.create_historical_record` and calling celery task inside to store history without blocking operation
> 
> ```python
> @app.task(queue=HISTORY_QUEUE)
> def save_history_record(app_name, model_name, manager_name, attrs, using):
>     model = django_apps.get_model(app_name, model_name)
>     history_manager = getattr(model, manager_name)
>     history_record = history_manager.model(**attrs)
>     history_record.save(using=using)
> ```

Thank you for your reply.

**Comment by jeking3** [comment]
It looks like this question was answered, so I am going to close it.

**Comment by cromig01** [comment]
@d1ffuz0r @Gauravwagh I wanted to circle back to this thread. How did you both end up overriding the `create_historical_record()` HistoricalRecords method? I'm currently trying to do this for a project where I want to send all historical record creations to celery. I've been reading about monkey patching and wanted to see if that's the right approach to override `create_historical_record` or if there's another way to override that class method
