### ISSUE TITLE
Add support for testing against multiple DBs

### ISSUE THREAD

**Issue by barm** [jazzband/django-simple-history#445]
**Problem Statement**
We've run into issues with regressions against DBs that are not currently tested.

**Describe the solution you'd like**
Run automated tests against:
* Postgres
* MySQL
* Sqlite

**Comment by JamesMura** [comment]
@barm I am taking a swipe at this one

**Comment by rossmechanic** [comment]
@JamesMura you have any luck with this one?

**Comment by rossmechanic** [comment]
Completed on #755 and #753
