### ISSUE TITLE
Utilize has_view_permission to let users with view permissions see the history

### ISSUE THREAD

**Issue by dgerritsen** [jazzband/django-simple-history#475]
**Problem Statement**
Currently, a user with view permissions can see the model instance itself, but not the history.

**Describe the solution you'd like**
A user with view, but not change permissions, to be able to view the history.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by erikvw** [comment]
What I am proposing / working on in PR #529 might address this.

**Comment by erikvw** [comment]
I have a PR I am submitting now that adds a settings attribute ``SIMPLE_HISTORY_ENFORCE_HISTORY_MODEL_PERMISSIONS``. When set set to ``True``, permissions assigned
to history models are assigned and evaluated explicitly and do not implicitly use the permissions from the concrete model.

This adds flexibility to allow/disallow access to history models by model.

**Comment by ddabble** [comment]
Linking the PR mentioned in the comment above, as it seems to resolve this issue. Please undo if that's not the case!
