### ISSUE TITLE
clear_duplicate_history command feature: allow to exclude some fields from `diff_against` check

### ISSUE THREAD

**Issue by MaximZemskov** [jazzband/django-simple-history#674]
Hey.

`clear_duplicate_history` command deletes only absolute identical instances, but there is an issue: if an instance has auto updated fields (e.g. version, updated_at) the command is not going to delete these duplicates

Is there a way to add a feature which would allow providing an exclude_list arg to the command and passing it to the diff_against method?

**Comment by rossmechanic** [comment]
@MaximZemskov, absolutely. Feel free to add a PR to update the `clean_duplicate_history` management command to allow for excluded fields. Think you would just have to update the `diff_against` method to ignore excluded fields

**Comment by MaximZemskov** [comment]
@rossmechanic https://github.com/jazzband/django-simple-history/pull/680
