### ISSUE TITLE
Add history_changed_fields field 

### ISSUE THREAD

**Issue by ayrtonlr** [jazzband/django-simple-history#681]
**Problem Statement**
In my project, I needed to get the date and the users who made changes in some specific field of my Model. So, to find that, I used the `diff_against` method between every pair of history to check if that specific field had changed and then grab the user and date.

**Describe the solution you'd like**
Add a field called `history_changed_fields` and populate this when the `history_type == "~"` with the name of the fields that has been changed from previous history. This will help when filtering the queryset to get just the histories when that specific field was changed, instead of looping through all history objects.

**Comment by zurtri** [comment]
I also am needing to provide a list of changes.

I have used the History Diffing in the docs: https://django-simple-history.readthedocs.io/en/2.10.0/history_diffing.html

But it is slow - as it makes many queries along the M2M relationships in the model. 

@ayrtonlr 's suggestion will solve the speed issue. 

Or is there a way to add some sort of prefetch_related to reduce the DB load?

**Comment by rossmechanic** [comment]
This has been raised before and requires us doing some work with dirty fields. It's something we'd like to get to but we've been resource constrained as of late. Going to close this as a duplicate issue

**Comment by raphodn** [comment]
For those who wish to have the same feature : 

1. add an extra field `history_changed_fields` to the HistoryModel ([documentation reference](https://django-simple-history.readthedocs.io/en/latest/historical_model.html?highlight=abstract#adding-additional-fields-to-historical-models))

```
from django.db import models
from django.contrib.postgres.fields import ArrayField

class HistoryChangedFieldsAbstractModel(models.Model):
    history_changed_fields = ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)

    class Meta:
        abstract = True

class MyModel(models.Model):
    (...)
    history = HistoricalRecords(bases=[HistoryChangedFieldsAbstractModel])
```

2. run migrations
3. configure the `post_create_historical_record` signal (I have a "complex" version, you can simplify as you wish)

```
HISTORY_CHANGED_FIELDS_TO_IGNORE = [
    # all models
    "id",
    "created",
    "updated",
    # django-simple-history
    "history_id",
    "history_date",
    "history_type",
    "history_change_reason",
    "history_user_id",
    "history_changed_fields",
]

@receiver(post_create_historical_record)
def post_create_historical_record_callback(sender, **kwargs):
    history_instance = kwargs["history_instance"]
    # update action
    if history_instance.prev_record:
        delta = history_instance.diff_against(history_instance.prev_record)
        changed_fields = delta.changed_fields
    # create action (most likely) : create changed_fields list manually
    else:
        model_fields = [field.name for field in sender._meta.fields if field.name]
        changed_fields = [k for k, v in history_instance.__dict__.items() if k in model_fields if v]
    # cleanup changed_fields
    changed_fields_cleaned = [
        field_name for field_name in changed_fields if field_name not in HISTORY_CHANGED_FIELDS_TO_IGNORE
    ]
    # assign & save
    history_instance.history_changed_fields = changed_fields_cleaned
    history_instance.save()
```
