### ISSUE TITLE
About related objects (onetoone, foreignkey, manytomany)

### ISSUE THREAD

**Issue by fx-it** [jazzband/django-simple-history#682]
Hello. I expect simplehistory to monitor related objects of deleted model. For example. There are A and B models.
```
class A(models.Model):
    history = HistoricalRecords()
class B(models.Model):
    a = ForeignKey(to=a, on_delete=models.CASCADE)
    historical = HistoricalRecords()
```

B has ForeignKey relation to A model. If instances of the models were deleted, b instance in history has only a_id int value, but can't get related  object immediately (like b.a). The same situation with the reverse relation (a.b_set.all()) - empty queryset. How should i correctly get related objects of instances in history? May be there is some way that i haven't noticed at the docs. I dont think that i have to create special properties or always call like:
```
a = A()
bs = B.history.filter(a_id=a.pk)
```
because in DRF serializers it will be terrible to override every relation to get related objects.

I used to try to override __getattribute__ in the BaseModel of all models class to get related objects, but it is in process (caught a recursion error).
It will be conveniently if there is an opportunity to get related objects from both of instance states (real and in history)

**Comment by rossmechanic** [comment]
We remove the FK constraint on historical objects so that history is unaffected if objects are removed. You have to query separately to get the objects defined by historical FKs.

**Comment by AbdullahDahmash** [comment]
I believe there is stronger reason. Otherwise, you can use `DO_NOTHING`, `SET_NULL`, `SET_DEFAULT`, etc.
