### ISSUE TITLE
Wrong link to docs in "About" (of this github project)

### ISSUE THREAD

**Issue by SzymonNastaly** [jazzband/django-simple-history#685]
**Describe the bug**
When viewing this project, there is the typical "About" section on the right. There the link [https://django-simple-history.readthedocs.org](https://django-simple-history.readthedocs.org) - it doesn't work anymore.
The correct link is given in the README on the bottom: [https://django-simple-history.readthedocs.io/](https://django-simple-history.readthedocs.io/).

**Error**
"Error 1016 - Origin DNS error" is returned by Cloudflare

**Environment (please complete the following information):**
 - OS: MacOS 10.15.5
 - Browser: Vivaldi, most recent

**Additional context**
I think just changing the link (for easier discoverability) would be great.

**Sorry if I made this issue in the wrong place or something, this is my first github issue ever**
BTW: This project is GREAT

**Comment by rossmechanic** [comment]
Hi @SzymonNastaly . Welcome! Glad you enjoy the project. Can you double check and see if this is still broken? From what I can tell, you seem to have hit a read the docs issue that's since been fixed. If it's still broken, can you add screenshots? Thanks!
