### ISSUE TITLE
Question: ForeignKey/ManyToMany support

### ISSUE THREAD

**Issue by sposs** [jazzband/django-simple-history#690]
Hi,
I can't find in the doc how those relationships are handled. In particular, if there is a ForeignKey to a Historical Model like in 
```python3
class A(models.Model):
    history = HistoricalRecords()
    some_parameter = models.CharField(max_length=10)

class B(models.Model):
    ref_to_a = models.ForeignKey(A, on_delete=models.CASCADE)
    history = HistoricalRecords()
```
I guess when doing
```python3
b = B.objects.all()[0]
b.ref_to_a
```
the object in ref_to_a is the last version of A.

Now, if I do
```python3
b = B.history.as_of(somedate)
b.ref_to_a
```
In that case, which version of ref_to_a is returned? Should I apply the same filter like in 
```python3
b.ref_to_a.history.as_of(somedate)
```
or is the filter propagated?

Similarly, how does that work for ManyToMany fields?

Thanks in advance, and this is a very good library!

**Comment by rossmechanic** [comment]
DSH doesn't currently handle keeping track of historical relationships for M2M fields. The FK references are always to base models (rather than to other historical models)
