### ISSUE TITLE
Clashes with reverse query name (related_query_name in Models)

### ISSUE THREAD

**Issue by Yorchly** [jazzband/django-simple-history#691]
When you have a field with a _related_query_name_ set, doing migrations (once you have added django simple history) will fail, telling you that **reverse query name for _'HistoricalName.field'_ clashes with reverse query name for _'ModelName.field'_**.

I have the next models:
```
class CommonModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    history = HistoricalRecords(
        inherit=True
    )

    class Meta:
        abstract = True
```

```
class Worker(CommonModel):
    name = models.CharField(max_length=25, help_text="Nombre del trabajador")
    surname = models.CharField(max_length=70, help_text="Apellidos del trabajador")
    entry_date = models.DateField(blank=True, null=True, help_text="Fecha de entrada en la empresa")
    check_in_hour = models.TimeField(blank=True, null=True, help_text="Hora de entrada del trabajador (Opcional)")
    check_out_hour = models.TimeField(blank=True, null=True, help_text="Hora de salida del trabajador (Opcional)")
    social_security_number = models.CharField(max_length=12, blank=True,
                                              help_text="Número de la seguridad social (Opcional)")
    user = models.OneToOneField(
        User,
        related_name="worker",
        related_query_name="worker",
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        help_text="Usuario de la plataforma asociado al trabajador (Opcional)"
    )

    def __str__(self):
        return "{}, {}".format(self.surname, self.name)
```

When I try to run `python manage.py makemigrations` I get the next error:

> workers.HistoricalWorker.user: (fields.E305) Reverse query name for 'HistoricalWorker.user' clashes with reverse query name for 'Worker.user'.
>  HINT: Add or change a related_name argument to the definition for 'HistoricalWorker.user' or 'Worker.user'.

I've been doing some research in google but I didnt find anything until inspecting the _'simple_history/models.py'_ code I found this in _copy_fields_ function line 278 (at the time of writing this issue):

```
# Override certain arguments passed when creating the field
# so that they work for the historical field.
field_args.update(
    db_constraint=False,
    related_name="+",
    null=True,
    blank=True,
    primary_key=False,
    db_index=True,
    serialize=True,
    unique=False,
    on_delete=models.DO_NOTHING,
)
```

Here I realized that no new _related_query_name_ was given to **field_args.update()** so, in the moment of creating the Historical model, the two models will have in the field the same _related_query_name_.

A possible **solution** (works for me) is to delete all _related_query_name_ added to fields of your model.

I don't know if this is really a bug, but the fact that I did not find anything it's come to my attention.

**Environment (please complete the following information):**
 - OS: Zorin OS 15.2
 - Django Simple History Version: 2.10.0
 - Django Version: 2.2
 - Database Version: PostgreSQL 10.12

**Comment by rossmechanic** [comment]
Hey @Yorchly! Why are you specifying both related_name and related_query_name? You should get the same result if you just specify `related_name`, and you'll no longer run into this bug.

**Comment by Yorchly** [comment]
> Hey @Yorchly! Why are you specifying both related_name and related_query_name? You should get the same result if you just specify `related_name`, and you'll no longer run into this bug.

Indeed, but I didn't know! Thanks for the reply :+1:

**Comment by sarimahm** [comment]
Have same issue
