### ISSUE TITLE
how to Save initial object content in history only when object is updated or deleted?

### ISSUE THREAD

**Issue by fcoppey** [jazzband/django-simple-history#692]
Hi,

I have a huge database and wanted to start using django-simple-history on it. After install I have applied python manage.py populate_history --auto to save initial object contents so that when an object is modified by a user I can revert to the initial version of this object. I have noticed that if I don't do that then when a user modifies an object the initial state of the object is not saved.

The problem is that python manage.py populate_history --auto will basically copy thousands of objects from my models in the history models although most of these objects will never be changed by anybody, therefore increasing the size of my database for backups by a lot... is there an option to only save the initial state of an object in the history WHEN and only when this object is modified-deleted?

Thanks a lot for this great feature, I hope we can find a solution to my issue.

Thanks

**Comment by rossmechanic** [comment]
there's a pre_create_historical_record signal that you could use to check if history exists for the object and create it if it doesn't exist

**Comment by fcoppey** [comment]
Excellent. Why not adopting this behavior by default then?

Le 3 août 2020 à 15:03, Ross Mechanic <notifications@github.com> a écrit :

﻿

there's a pre_create_historical_record signal that you could use to check if history exists for the object and create it if it doesn't exist

**Comment by fcoppey** [comment]
I'm trying to use pre_create_historical_record but there is not much doc related to that. would you have an example of how to use it?

thanks

**Comment by fcoppey** [comment]
sorry to come back on this but after a few weeks of use I feel like it would be great to start saving objects in history once they are really modified and not when they are created. Imagine that I have a mysql database with a 200 columns table and 500'000 objects, django-simple-history will clone this table and double the size of the database at start even when just a few of these objects will finally be edited and modified by users... I think there is something to optimise here no?

**Comment by rossmechanic** [comment]
It's an optimization that you can make. However, it's difficult to make part of the library as you first have to check to see whether or not the instance already has history, and then you need to figure out whether the object is being added or updated. It's something that, to me, makes more sense for you to handle in your calls.

**Comment by fcoppey** [comment]
I understand, I managed to make it work for my case but it was quite tricky indeed…

Thanks for amazing work. Soooo useful.

On 26 Aug 2020, at 16:59, Ross Mechanic <notifications@github.com<mailto:notifications@github.com>> wrote:



It's an optimization that you can make. However, it's difficult to make part of the library as you first have to check to see whether or not the instance already has history, and then you need to figure out whether the object is being added or updated. It's something that, to me, makes more sense for you to handle in your calls.
