### ISSUE TITLE
How to revert deleted objects in django admin?

### ISSUE THREAD

**Issue by fcoppey** [jazzband/django-simple-history#693]
Hi again,

is there a way to see deleted objects in django admin and revert them? Would be awesome...

thanks

**Comment by georgek** [comment]
Generally you shouldn't delete stuff from your databases, you should instead flag it as "deleted" or "inactive". See the built in `User` models for an example of this. The main reasons to need to delete are legal reasons like for GDPR compliance, but in that case you would really want all traces to be gone (including history).

**Comment by rossmechanic** [comment]
Agree with @georgek. This is something that would be fairly straightforward to build. You have access to all deleted objects in the history table, and reverting one just requires getting the base model instance and saving it.
