### ISSUE TITLE
Delete a column, the operation record(+,-,~) related to this column has not been deleted

### ISSUE THREAD

**Issue by gonglei1999** [jazzband/django-simple-history#696]
Hi,
If I delete a column in the table, the corresponding column in the record table is also deleted. But the operation records (+, -, ~) generated by this column are not deleted, which will cause some problems

**Comment by rossmechanic** [comment]
That's on purpose. If you want to cascade deletion to historical records, you can do the following:

```
class MyModel(models.Model):
    history = HistoricalRecords(cascade_delete_history=True)
```
