### ISSUE TITLE
IntegrityError FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by kwhandy** [jazzband/django-simple-history#697]
I try to use this package for one-tone-field's related model, this is great. but when I try to delete the user model(I mean delete entire user related model) it return constraint failed.

here is my model structure:
+ User
   + Model Parent(one-to-one field with User, but this have child)
      - Model Child(one-to-one field with Model Parent, WITHOUT HistoricalRecords()
      - Model Child(one-to-one field with Model Parent, WITH HistoricalRecords()

this make me spend almost 12 hours to figure out what happen, and here's the result:
1. When i try to make the entire model but EXCLUDE the HistoricalRecords(), it's just deleted smoothly
2. When i try to make the entire model but INCLUDE the HistoricalRecords(), it's always return **IntegrityError FOREIGN KEY constraint failed**
3. If i try to delete Model Parent model manually first then delete the User model, it's just deleted smoothly

Can someone help me to solve this? I really need this package for each Model Child model

**Environment:**
 - OS: MacOS 12
 - Browser (if applicable): CHROME
 - Django Simple History Version: 2.10.0
 - Django Version: 2.2.7
 - Database Version: SQLite 3+(because just for dev)

**Comment by rossmechanic** [comment]
This is because the historical model has a foreign key to your user model (that's how we know who edited a row). You can get around this by following the instructions [here](https://django-simple-history.readthedocs.io/en/latest/user_tracking.html#manually-track-user-model) for manually tracking a user model.
