### ISSUE TITLE
Feature: Direct access to related model history from history object

### ISSUE THREAD

**Issue by cfytrok** [jazzband/django-simple-history#700]
```python
class Parent(models.Model):
    name = models.CharField(max_length=255)
    log = HistoricalRecords(related_name='history')

class Child(models.Model):
    name = models.CharField(max_length=255)
    log = HistoricalRecords(related_name='history')
    parent = models.ForeignKey(Parent,on_delete=CASCADE)

bob=Parent.objects.create(name='Bob')
alice=Child.objects.create(name='Alice', parent=bob)
bob.delete()

Child.log.filter(parent__name='Bob').last() # not work
Child.log.last().parent # not work
Child.log.last().parent_id # work
```

Last line doesn't work, because bob object doesn't exist. But bob and alice history records exists; history contains parent_id for deleted Child; and Parent history also contains records with ids.
It would be greate to have access to related model history in filters and models like so:
```python
Child.log.filter(parent_history__name='Bob').last()
or
Child.log.last().parent_history_set.all()
```

**Comment by rossmechanic** [comment]
Just need to add a `related_name` to the `HistoricalRecords`:

https://django-simple-history.readthedocs.io/en/latest/querying_history.html#filtering-data-using-a-relationship-to-the-model

**Comment by cfytrok** [comment]
Please, explain in more detail. I used related_name, but it doesn't work with deleted items in related fields. See my example.

**Comment by rossmechanic** [comment]
Not sure I'm following your question exactly. Can you try to explain more clearly?

**Comment by cfytrok** [comment]
I edited example in my first comment. Hope it is more clear.

More specifically, here is my task.
I have local DB and REST server. I need to send local changes to server. After cascade deleting objects in local DB i need to send ids of deleted objects to the server. 

I can not send one delete request for all deleted Choice objects. It should be one request per Question, because Questions and related Choices are stored on different servers (server_id field).
How can I filter out all deleted Choices, that are stored on server with id=1?

**Comment by rossmechanic** [comment]
Oh I see. This is expected behavior. We remove the foreign key constraint when we write to the history table so that if you were to delete the base object (in this case, the choice), then it wouldn't also delete the historical row (or make it null).

**Comment by cfytrok** [comment]
It seems my english is too bad to explain what I want. But I'll try again)

Look at this statement:
```python
choices = Choice.objects.filter(question__question_text='What's up?').values_list('id', flat=True)
```
It works fine if Questions and Choices exists.
If i need to filter Choices in deleted Questions, I have to use this statements:
```python
question_id = Question.log.filter(question_text='What's up?', history_type='-').last().id
deleted_choices = Choice.log.filter(question_id=question_id).values_list('id', flat=True)
```
Is it possible to simplify this statements?

**Comment by rossmechanic** [comment]
It's not, because the historical tables don't have explicit foreign keys
