### ISSUE TITLE
Summary of Recent Changes

### ISSUE THREAD

**Issue by rotherfuchs** [jazzband/django-simple-history#701]
**Problem Statement**
As an Admin, I'd like to immediately see what models were recently changed without having to navigate to each one and look for changes.

**Describe the solution you'd like**
I'd see an SimpleHistory Admin page that generates an summed overview over all models that were registered via `HistoricalRecords()` and chronologically lists all changes, also allowing to filter by username, model or time.

**Comment by rossmechanic** [comment]
You're welcome to build it, but I don't think that makes sense as part of the library. You'll have N queries where N is the number of models that you have historical records registered on. It'll get pretty slow, pretty quickly
