### ISSUE TITLE
`bulk_update_with_history` to support alternative model managers

### ISSUE THREAD

**Issue by georgek** [jazzband/django-simple-history#703]
**Problem Statement**
I have some models where the default model manager (`objects`) doesn't include all objects (it doesn't include "inactive"/deleted objects). However, `bulk_update_with_history` assumes that the model manager to use is `objects` which means it can never update those objects which are not included.

**Describe the solution you'd like**
A way to pass an alternative model manager.

**Describe alternatives you've considered**
Two options I can think of:

- Pass optional model manager (backwards compatible):
```
def bulk_update_with_history(
    objs, model, fields, batch_size=None, default_user=None, default_change_reason=None, manager=None,
):
    history_manager = get_history_manager_for_model(model)
    with transaction.atomic(savepoint=False):
        model_manager = manager or model.objects
        model_manager.bulk_update(
            objs, fields, batch_size=batch_size,
        )
        history_manager.bulk_history_create(
            objs,
            batch_size=batch_size,
            update=True,
            default_user=default_user,
            default_change_reason=default_change_reason,
        )
```
- Pass manager instead of model (breaking):
```
def bulk_update_with_history(
    objs, model_manager, fields, batch_size=None, default_user=None, default_change_reason=None,
):
    history_manager = get_history_manager_for_model(model_manager.model)
    with transaction.atomic(savepoint=False):
        model_manager.bulk_update(
            objs, fields, batch_size=batch_size,
        )
        history_manager.bulk_history_create(
            objs,
            batch_size=batch_size,
            update=True,
            default_user=default_user,
            default_change_reason=default_change_reason,
        )
```

**Comment by rossmechanic** [comment]
Hm. Good catch. I don't want to introduce a breaking change, so I'm more comfortable with the first solution with validation that the manager's model is the model that was passed in. Happy to approve a PR if you want to add it
