### ISSUE TITLE
raise PermissionDenied in history_view

### ISSUE THREAD

**Issue by rodrigondec** [jazzband/django-simple-history#704]
# I'm willing to open PR

related to #631 ?

**Describe the bug**
In the history view it's verified if it has `self.has_change_permission`

https://github.com/jazzband/django-simple-history/blob/7b1538908bca61ab2c0574c2d44ff5c485faa978/simple_history/admin.py#L73

Why does it need change permission to view the history?

> I'm not talking about the `history_form_view`!

I'm changing the method `has_change_permission` to disable edit's.

I'm receiving a 403 Forbidden because of this!

**To Reproduce**
1. Overwrite the method has_change_permission in the AdminModel

```python
    def has_change_permission(self, request, obj=None):
        """
        Desabilita alteração da entidade
        """
        return False
```
2. Go to admin
3. Go to entry of the model
4. Access `history`

**Expected behavior**
I was expecting to view my history!

**Screenshots**
![image](https://user-images.githubusercontent.com/3301060/90909365-053d3980-e3ac-11ea-8ccd-cbbb8c79385a.png)

![image](https://user-images.githubusercontent.com/3301060/90909379-0bcbb100-e3ac-11ea-9ea0-96974374d058.png)

![image](https://user-images.githubusercontent.com/3301060/90909411-15edaf80-e3ac-11ea-998b-2903efc060e1.png)

## Without the overwrite on has_change_permission
![image](https://user-images.githubusercontent.com/3301060/90909522-3d447c80-e3ac-11ea-8859-09bf834b699d.png)

**Comment by vied12** [comment]
Hello,

For now I'm doing like this : 

```python
def has_change_permission(self, request, obj=None):
        # special rule for history, otherwise it doesn't show up
        if resolve(request.path_info).url_name == 'core_wescaleactivity_history':
            return True
        return False
```

**Comment by rossmechanic** [comment]
Yep this is related to #631 and should be addressed in the next version of DSH

**Comment by erikvw** [comment]
see #1017
