### ISSUE TITLE
Querying history on a related model with as_of

### ISSUE THREAD

**Issue by dwasyl** [jazzband/django-simple-history#715]
Hi all,

I've always made good use of the `as_of` function for pulling up historical instances. However, I was recently trying to pull up a series of related objects as of a particular day, where the same thing for related querysets would have been really useful.

The idea would be something like: `Pizza.toppings.as_of(date)` if the model `Pizza` had a related object `Topping` with a foreign key back to `Pizza`.

In the meantime, I ended up querying the history against the model for anything with that foreign key and then having to do individual `.as_of(date)` lookups for each object. Just seemed like there could be a more efficient way of doing this (or perhaps there already is and I missed it).

**Comment by rossmechanic** [comment]
Planning on working on this in the ticket you linked.

**Comment by dwasyl** [comment]
Great, thanks for the followup!
