### ISSUE TITLE
Add option to exclude indices from being created for history tables

### ISSUE THREAD

**Issue by wrvdklooster** [jazzband/django-simple-history#720]
**Problem Statement**
We have some rather large tables where we use django-simple-history. The total size of the history tables is quite large but also the indices created. We do not use (most of) the indexes in the history table. It would be great if we could exclude them from being created.

This will save performance while updating the history table but especially will save us disk space. Expected disk space to be saved in our case would be over 30Gb.

**Describe the solution you'd like**
An option to exclude indices like we exclude fields. Not sure what best solution would be.

**Describe alternatives you've considered**
None.

**Additional context**
NA.

**Comment by nick-cobalt** [comment]
I'd personally prefer for performance reasons that there be an option to default to not indexing any of the additional fields for the historical table, but having at least some ability to skip indexes would definitely be helpful.
