### ISSUE TITLE
providing_args deprecation warning Django 3.1

### ISSUE THREAD

**Issue by deeprave** [jazzband/django-simple-history#723]
**Describe the bug**
Django 3.1 issues this deprecation warning:
```
..../simple_history/signals.py:4: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
    pre_create_historical_record = django.dispatch.Signal(
```
... and same again on line 14 for post_create_historical_record.

**To Reproduce**
1. run the addon using Django 3.1
2. run some test or action which triggers the pre and/or post signal
4. See deprecation warning

**Expected behavior**
No deprecation warning :-)

**Environment (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser N/A (I see this in pytest output)
 - Django Simple History Version: 2.11.0
 - Django Version: 3.1.2
 - Database Version: postgresql 12.4

**Additional context**
Should be reproducible anywhere.

**Comment by ThePumpingLemma** [comment]
This was already fixed in https://github.com/jazzband/django-simple-history/pull/702

We're planning on cutting release within the next week or so.

**Comment by deeprave** [comment]
Awesome, thanks!

**Comment by rituraj123db** [comment]
/home/ideal48/Projects/order_service/venv/lib/python3.8/site-packages/safedelete/signals.py:5: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is pure documentation, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
    post_undelete = ModelSignal(providing_args=["instance", "using"], use_caching=True)
