### ISSUE TITLE
History Diffing for Fields With Foreign Keys Returns Primary Key Values And Not The Name of the Field.

### ISSUE THREAD

**Issue by justAcoderguy** [jazzband/django-simple-history#725]
`class InternalPayment(models.Model):
    slug = models.CharField(max_length=100,unique=True,null=True ,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE )
    payment_for = models.ForeignKey(Payment_For,on_delete=models.CASCADE, null=True, blank=True)
    history = HistoricalRecords()`

Suppose I have this model, then if I use history diffing for the field "payment_for", it will show "The field payment_for has changed from 3 to 2" as an example.

The payment_for model is below :
`class Payment_For(models.Model):
    payment_for = models.CharField(max_length=100, null=False, blank=False)
    def __str__(self):
        return self.payment_for`

It should return the __str__ representation. As an example : "The field payment_for has been changed from Abhishek to SomeoneElse"

Thanks !

**Comment by rossmechanic** [comment]
The historical table doesn't enforce foreign key constraints and only keeps track of the ID. this is expected behavior. If you want to take that ID and grab the str representation from the related table, you're more than welcome to :)
