### ISSUE TITLE
Would you **please** add m2m support?

### ISSUE THREAD

**Issue by smileservices** [jazzband/django-simple-history#740]
**Problem Statement**
Handling m2m fields is very important for many projects. I like youre package approach to solving the history problem but it's so frustrating that it doesn't support this simple m2m field.

**Describe the solution you'd like**
Just implement it already!

**Describe alternatives you've considered**
There is a pull request since 2018 for this.

**Additional context**
I'll build a django-simple-history-m2m myself if you won't do it

**Comment by ThePumpingLemma** [comment]
We'll happily review an updated PR for m2m support.

**Comment by sobadgirl** [comment]
Is there any updates for m2m support? i'm looking for some information  about it, if so, please let me know. thx.
