### ISSUE TITLE
Queryset as_of history performance issues

### ISSUE THREAD

**Issue by TyrantWave** [jazzband/django-simple-history#758]
**Describe the bug**
The current implementation of a queryset as_of does the checks for changes (And removal of "-" history types) purely in a python set & generator - looping over every single item in the original queryset.

On sufficiently large querysets, this can take a significant amount of time to get a full set of historical models for a queryset at a given point in time.

**To Reproduce**
Have a large (Hundreds of thousands of records or more) queryset, and attempt to work on the entire queryset (For example, generating a set of diffs from a point of time to current over a whole set)

On my data, with ~47,000 items and ~80,000 historical rows, getting a set of changes for one filtered set can take up to 20 minutes.

(I'm aware of the other ticket to add filtering to these querysets and am planning on making a pull request for that in the future)

**Expected behavior**
Generation of the history should be done utilising the database where possible for significant speed gains.

**Environment (please complete the following information):**
 - OS: Mac / Ubuntu 18.04 Docker
 - Django Simple History Version: 2.8.0 ~ latest
 - Django Version: 3.0.3
 - Database Version: PostgreSQL 11

**Comment by jeking3** [comment]
Does the composite indexing I added in #863 do anything to address this?
