### ISSUE TITLE
HistoricalRecords unable to get current user if action on model instance is initiated by celery task 

### ISSUE THREAD

**Issue by gosiawolniewicz** [jazzband/django-simple-history#780]
I am using django-simple-history and it works fine, however I have a problem in using it if action to do on my model instance is initialized by a celery task, which works offline in my service.

I need a piece of advice what shall I do. The situation is that when I try to e.g. delete the instance of my model from the celery task code I don't have user's session established. Therefore HistoricalRecords can't get information about logged in user and created historical record has user id missing. In my scenario I need historical records to be full, including user id.

I can't pass request object to celery task, because only simple data types (serializable to JSON) are accepted. So I pass username.

I tried to "mock" a request, assign it username and pass it to the serializer of my model, but no avail.

        user = get_object_or_404(RohubUser, username=username)
        logger.debug(f'Upload operation was submitted by user {user}')

        request = HttpRequest()
        request.user = user

        logger.debug('RO delete starting')
        instance = ResearchObject.objects.get(identifier=kwargs["identifier"])
        ro_serializer = serializers.ResearchObjectSerializer(context={'request': request}, instance=instance, many=False)
        ro_serializer.ro_destroy(instance)
        logger.debug('RO delete finished with success')

I would be grateful for any hints.

Best regards,
Gosia

**Comment by benedikt-bartscher** [comment]
I had the same problem with django-q and solved it like this:

models.py
```
    changed_by = models.ForeignKey(
        'auth.User',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    history = HistoricalRecords()

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value
```

```
def async_func(obj, user):
    obj.changed_by = user
    print('i am doing async stuff')
```

**Comment by jeking3** [comment]
This does not seem like a failing of django-simple-history; in a celery task you are likely running on a different machine and certainly outside the request context.  The ability to get the current user in that environment will require you to pass it to your task and set it.

If you send the user id of the user who made the change, you can set it in the historical object as @benedikt-bartscher detailed.

What would be nice is a documentation update showing this solution for celery tasks that generate history.
