### ISSUE TITLE
How to access the history model in models.py if simple_history.register() is used.

### ISSUE THREAD

**Issue by AndiDomi** [jazzband/django-simple-history#781]
I am using django-simple-history as in the simple example below:

`models.py`
```
class A(models.Model):
    id = models.UUIDField(primary_key=True, db_column="uuid", default=uuid.uuid4, editable=False)
    
class B(models.Model):
    id = models.UUIDField(primary_key=True, db_column="uuid", default=uuid.uuid4, editable=False)
 
 # define a custom field for  a reverse rl to the history table of A
class HistoryB(django.db.models.Model):
    history_a = django.db.models.ForeignKey(models.A.history.model, db_column="history_alert",
                                                related_name='b', on_delete=django.db.models.PROTECT, null=True)

    class Meta:
        abstract = True
```

On `translations.py`
```
translator.register(models.A, ATranslationOptions)
translator.register(models.B, BTranslationOptions)

simple_history.register(models.A, inherit=True)
simple_history.register(models.B, inherit=True, bases=[models.HistoryB)
```
And then adding the Foreignkey  to the history table of `B`  during `pre_create_historical_record`.
As you can already imagine this creates an error tho as we are trying to reference a model which is not created yet (as it is created in `translations.py`) and throws an error.
A solution would be to define `HistoryB` in translations.py right after `A` is registered for history but this is not in line with the philosophy of django where each model should be detailed in `models.py`
Is there any way to fix this or am I missing some options to fix this ?

**Comment by AndiDomi** [comment]
Solved by creating 
`history = HistoricalRecords()` in `class A`
then registering not only `translator.register(models.A)` but also `translator.register(models.A.history.model)`

**Comment by chancellor-dev** [comment]
@AndiDomi Hi. If you do that, I would like to know if model B tracks the changes of model A.
