### ISSUE TITLE
What is the recommended way to get the most recent HistoricalModel instance? 

### ISSUE THREAD

**Issue by petr-mitsel** [jazzband/django-simple-history#803]
As mentioned in https://github.com/jazzband/django-simple-history/issues/113, the documentation still states that `most_recent` and `as_of` return instances of `HistoricalModel`, but they actually still return instances of the Model class itself. 

Pending an update to the documentation, what is the recommended way of actually getting the most recent `HistoricalModel` instance?

**Comment by wizpig64** [comment]
I tried to modify `as_of` to get this to work several years ago in #255, but the maintainers didn't seem interested in giving direct access to the historical instances. This might not be the 'recommended' way, but you could subclass `HistoryManager` and create a method nearly identical to `as_of`, and just remove the `.instance` at the end [here](https://github.com/jazzband/django-simple-history/blob/master/simple_history/manager.py#L87) to get it to spit out the `HistoricalModel` instance.

**Comment by cachitas** [comment]
As of verison 3.0.0, what is the advantage of using `obj.history.most_recent()` vs `obj.history.latest().instance` vs `obj.history.latest().history_object`?
I am trying to understand the internals and looks like all these options account for excluded fields and instantiate the model similarly.

I was trying to get the most recent version and its corresponding history_id at the same time. Are there any pitfalls in the following snippet?

```python
most_recent_record = obj.history.latest()
most_recent = most_recent_record.instance
history_id = most_recent_record.history_id

# vs

most_recent = obj.history.most_recent()
# no way to get history_id :(
```

**Comment by jeking3** [comment]
If I need the most recent historical model for something I query history directly using the appropriate filter constraints.  The code in @cachitas comment above works.

In #880 I proposed that all historic instances get a `_history` property that allows one to retrieve the Historical<Model> from the <Model>.
