### ISSUE TITLE
verbose_name_plural for historical model

### ISSUE THREAD

**Issue by sergiusnick** [jazzband/django-simple-history#812]
**Problem Statement**
Now HistoricalRecords support only "verbose_name" parameter. But django supports "verbose_name_plural" for models. In most cases "verbose_name" is enough, but there are some words, that have plural form more complex than "single"+s, especially in languages diifer from English 

**Describe the solution you'd like**
Add parameter "verbose_name_plural" to HistoricalRecords

**Comment by jeking3** [comment]
Fixed by #873
