### ISSUE TITLE
Django 3.2 please bump release to support it (TextFields db_collation)

### ISSUE THREAD

**Issue by rh0dium** [jazzband/django-simple-history#813]
Django 3.2 was released.  The main branch has a fix ([f5ffdd55a](https://github.com/jazzband/django-simple-history/commit/f5ffdd55aa21b053100aa7ec9d690d32be9733a8)) for TextField support.

Could we please get a 2.12.1 release to support this.

**Comment by jcushman** [comment]
@treyhunner @rossmechanic , just a nudge -- you're the Jazzband project leads who can make a release, right?

**Comment by barm** [comment]
Head's up that we've got an incoming PR to prepare the next release https://github.com/jazzband/django-simple-history/pull/819

**Comment by barm** [comment]
This is now released on pypi!
