### ISSUE TITLE
Cannot resolve keyword 'history' into field. 

### ISSUE THREAD

**Issue by alvarolloret** [jazzband/django-simple-history#833]
**the bug**
Model with two managers does not seem to detect the history field.
```
class BookMark(models.Model):
    created_at = models.DateTimeField("Created at", auto_now_add=True)
    history = HistoricalRecords()

    objects = models.Manager()
    table_manager = BookMarkManager()
```

**Expected behavior**
When calling this I'm supposed to get the results
```
queryset=BookMark.objects\
                    .filter(history__history_date__gt=last_week)
```
**error received**
Cannot resolve keyword 'history' into field. Choices are: created_at

**Environment (please complete the following information):**
 - OS: UBUNTU 20
 - Django Simple History Version: 3
 - Django Version: 2.2
 - Database Version: MySQL 8

**Comment by raphodn** [comment]
I'm facing the same issue, how did you solve it ?
- in my model : `history = HistoricalRecords()` + a manager
- when doing a simple `Model.objects.filter(history__history_user=1)` I get this error : `Cannot resolve keyword 'history' into field`
