### ISSUE TITLE
`clean_duplicate_history` uses default model manager, which may filter out relevant instances

### ISSUE THREAD

**Issue by OmenApps** [jazzband/django-simple-history#838]
**Describe the bug**
When using `clean_duplicate_history`, and models with a default manager (objects = XYZ) which filters out model instances may fail to correctly de-duplicate history (because it can't see all of the instances).

This is very similar to issue #703 for `bulk_update_with_history` (and its fix, #709).

**To Reproduce**
1. Install django-simple-history
2. Add a model manager which applies filtering to a model which uses django-simple-history
3. Run `clean_duplicate_history --auto`
4. De-duplication of the model may be incomplete or not perform any work at all

**Expected behavior**
`clean_duplicate_history` should use Django's base manager to ensure all model instances are checked for duplicates.

_Note: #804 is the potential fix for this issue_

**Comment by ddabble** [comment]
Closing, now that #1115 (replacing #804) was merged.
