### ISSUE TITLE
History restoration is not working properly

### ISSUE THREAD

**Issue by IamMiracleAlex** [jazzband/django-simple-history#842]
**Describe the bug**
Thanks for this awesome package.. 
I noticed that when you create a history, and want to revert the changes. This does not work properly. It does not restore the previous value, it instead returns the current value. 

**To Reproduce**
1. Integrate django-history, go to the admin
2. Make a change to the a model
3. Revert the change
4. See that the change is not reverted

**Expected behavior**
A when a model instance changes, and a revert action is applied, it is expected that the change is reverted

**Screenshots**
![image](https://user-images.githubusercontent.com/46989723/122763950-d4ad8100-d296-11eb-8a33-3e0a46a9f4a9.png)

**Environment (please complete the following information):**
 - OS:  MacBook Pro, 10.15 
  - Browser (if applicable): Chrome
 - Django Simple History Version: 3.0.0
 - Django Version: 3.1
 - Database Version: PostgreSQL 12

**Additional context**

**Comment by IamMiracleAlex** [comment]
@treyhunner @macro1 @rossmechanic 
Please take a look

**Comment by tim-schilling** [comment]
@IamMiracleAlex can you show us the values of all the fields in each of those historical records?

**Comment by ddabble** [comment]
Closing stale issue.
