### ISSUE TITLE
Historical model doesn't include fields inherited from superclass

### ISSUE THREAD

**Issue by AndrewHows** [jazzband/django-simple-history#87]
I ran into this issue trying to add simple_history to a model using django-mptt ( https://github.com/django-mptt/django-mptt/ )

The model in question extends MPTTModel, which adds the fields `lft`, `rght`, `tree_id` and `level` to the model. However, if I try and save the model, it fails, with the exception:

```
TypeError: 'rght' is an invalid keyword argument for this function
```

I did some digging, and when the create_history_model() executes, these fields did not exist. The contents of model._meta.fields at that time was:

```
[<django.db.models.fields.AutoField: id>, <django.db.models.fields.CharField: name>, <django.db.models.fields.SlugField: url>, <django.db.models.fields.CharField: code>, <mptt.fields.TreeForeignKey: parent>, <django.db.models.fields.TextField: hidden_js>, <django.db.models.fields.related.ForeignKey: faculty>]
```

However, if I opened up a django shell, and output the contents of the same variable, I got:

```
[<django.db.models.fields.AutoField: id>, <django.db.models.fields.CharField: name>, <django.db.models.fields.SlugField: url>, <django.db.models.fields.CharField: code>, <mptt.fields.TreeForeignKey: parent>, <django.db.models.fields.TextField: hidden_js>, <django.db.models.fields.related.ForeignKey: faculty>, <django.db.models.fields.PositiveIntegerField: lft>, <django.db.models.fields.PositiveIntegerField: rght>, <django.db.models.fields.PositiveIntegerField: tree_id>, <django.db.models.fields.PositiveIntegerField: level>]
```

Which _does_ have the additional fields. My conclusion is that the class has not yet been properly initialized at the time class_prepared is fired.

**Comment by rossmechanic** [comment]
It's not a third party model but it's inheriting from a third-party model. Instead of adding `HistoricalRecords` to the model, try adding `register(ModelName)` outside of the model definition (either in your `models.py` file or in the `ready` function of your `AppConfig`. Let me know if you run into any issues with that. @irrg

**Comment by irrg** [comment]
@rossmechanic I don't know where my brain went on this one…that's a super easy solution. Seems to be sticking. Will report back if anything wonky happens in relation to django-simple-history. Thanks!

**Comment by irrg** [comment]
So far so good, except that I'm curious how the Original Poster dealt with needing to register his model with both SimpleHistoryAdmin and DjangoMpttAdmin… Down the rabbit hole.

Either way, the issue with the superclass is resolved with the `register` workaround.

**Comment by AndrewHows** [comment]
Four years ago - sorry, I can't even remember what project this was for. I might not even have access to the source code any more, if it was at a previous job.

**Comment by epineda** [comment]
Here the new link for [register](https://django-simple-history.readthedocs.io/en/latest/quick_start.html#track-history-for-a-third-party-model) documentation.

But there are more information in the source code:
https://github.com/treyhunner/django-simple-history/blob/master/simple_history/__init__.py
