### ISSUE TITLE
Chasing ForeignKeys across a historic timepoint

### ISSUE THREAD

**Issue by jeking3** [jazzband/django-simple-history#880]
**Problem Statement**
I found an interesting way to allow historic instances to load their foreign keys by value, assuming the foreign key's model is also being handled by django-simple-history.  I wanted to share, and see if it sparks any further ideas from people who know the code better.

**Related Issues**

I found a couple issues that are related.  Essentially what I did in this issue as a thought exercise allows you to use foreign keys of as_of instances, as long as both tables use simple history.

#118
#17

**Describe the solution you'd like**
If table A and B are both historic, and A has a foreign key relationship to B (let's call this field `foo`), simple_history will drop the foreign key but maintain the _id field.  If one queries the history on table A and gets an instance, if the corresponding record in table B has already been deleted then you end up with a `DoesNotExist` error.

What I would like to see is that if you delete the record from B, then try to call A.history.earliest().instance.foo, it would find the corresponding record from B before it was deleted and return an instance of it.

**How I solved this locally**
First, I augmented `get_instance` to inject the historical record into the resulting instance as `_history`:

```
$ git diff before..after
diff --git a/simple_history/models.py b/simple_history/models.py
index de3762b..dc5763b 100644
--- a/simple_history/models.py
+++ b/simple_history/models.py
@@ -32,6 +32,9 @@ except ImportError:
 
 registered_models = {}
 
+# when converting a historical record to an instance, this attribute is added
+# to the instance so that code can reverse the instance to its historical record
+SIMPLE_HISTORY_REVERSE_ATTR_NAME = "_history"
 
 def _default_get_user(request, **kwargs):
     try:
@@ -393,7 +397,11 @@ class HistoricalRecords:
                     pass
                 else:
                     attrs.update(values)
-            return model(**attrs)
+            result = model(**attrs)
+            # this is the only way external code could know an instance is historical
+            setattr(result, SIMPLE_HISTORY_REVERSE_ATTR_NAME, self)
+            return result
 
         def get_next_record(self):
             """
diff --git a/simple_history/tests/tests/test_models.py b/simple_history/tests/tests/test_models.py
index bb8abef..5516e3b 100644
--- a/simple_history/tests/tests/test_models.py
+++ b/simple_history/tests/tests/test_models.py
@@ -16,7 +16,7 @@ from django.urls import reverse
 
 from simple_history import register
 from simple_history.exceptions import RelatedNameConflictError
-from simple_history.models import HistoricalRecords, ModelChange
+from simple_history.models import HistoricalRecords, ModelChange, SIMPLE_HISTORY_REVERSE_ATTR_NAME
 from simple_history.signals import pre_create_historical_record
 from simple_history.tests.custom_user.models import CustomUser
 from simple_history.tests.tests.utils import (
@@ -359,6 +359,13 @@ class HistoricalRecordsTest(TestCase):
             },
         )
 
+    def test_reverse_historical(self):
+        """Tests how we can go from instance to historical record."""
+        document = Document.objects.create()
+        historic = document.history.all()[0]
+        instance = historic.instance
+        self.assertEqual(getattr(instance, SIMPLE_HISTORY_REVERSE_ATTR_NAME).history_date, historic.history_date)
+
     def test_specify_history_user(self):
         user1 = User.objects.create_user("user1", "1@example.com")
         user2 = User.objects.create_user("user2", "1@example.com")
```

Once that was done, I tried to find a way to augment django without monkey patching it, but I wasn't able to as of yet.  I was trying to replace the Meta._base_manager so that it would return history if a historic instance, or objects if not.  This would not be sufficient however since you need to run an `as_of` query.  So what I did instead is this rather hacky solution:

```
from django.db.models.fields.related_descriptors import ForwardManyToOneDescriptor
from django.db.models.fields.related_descriptors import ReverseOneToOneDescriptor
from simple_history.models import SIMPLE_HISTORY_REVERSE_ATTR_NAME

original_rood_get_queryset = getattr(ReverseOneToOneDescriptor, "get_queryset")
original_fmod_get_queryset = getattr(ForwardManyToOneDescriptor, "get_queryset")


def historic_aware_rood_get_queryset(rood: ReverseOneToOneDescriptor, **hints):
    instance = hints.get("instance")
    if instance:
        history = getattr(instance, SIMPLE_HISTORY_REVERSE_ATTR_NAME, None)
        if history:
            return rood.related.related_model.history.as_of(history.history_date)
    return original_rood_get_queryset(rood, **hints)


setattr(ReverseOneToOneDescriptor, "get_queryset", historic_aware_rood_get_queryset)


def historic_aware_fmod_get_queryset(fmod: ForwardManyToOneDescriptor, **hints):
    instance = hints.get("instance")
    if instance:
        history = getattr(instance, SIMPLE_HISTORY_REVERSE_ATTR_NAME, None)
        if history:
            return fmod.field.remote_field.model.history.as_of(history.history_date)
    return original_fmod_get_queryset(fmod, **hints)


setattr(ForwardManyToOneDescriptor, "get_queryset", historic_aware_fmod_get_queryset)
```

I put that code into a file and force it to load during serilalizer `__init__` in my project.  Now when the code in django's relation processing asks for a queryset, it will get back a queryset that has been `as_of` filtered using the `history_date` that was in the historical record behind the instance.  This also has a benefit of allowing you to know if an instance is derived from history or not, which might be useful as well.  I noticed this does not work for chained lookups however, for example if you have a `get_object_or_404` that uses a filter like  `b__c__id` it doesn't seem to see "b" in this case.  I'm sure with another patch that could be made to work as well.

Any thoughts on how to improve this would be quite welcome.  Thanks.

**Comment by jeking3** [comment]
I was able to subclass ForeignKey to make a HistoricForeignKey that will chase related objects using the same as_of timepoint from the relatee.  To do this I had to modify django-simple-history as I pointed out above, adding the _history property to any historical instance (so I know it is historic) and adding an _as_of to each of those.  That is enough information to override get_queryset on ForwardManyToOne (easy) and ReverseManyToOne (hard) relationships, locking the relationship chase to the same timepoint.

I'm hoping that this PR, and then the combination of my _history and _as_of, and this new work on subclassing HistoricForeignKey will allow natural historic relationship chasing if both sides of the relation are historic.

**Comment by jeking3** [comment]
This work depends on #866 so will complete that first.

**Comment by utapyngo** [comment]
A stupid question. How to make this relation work historically using a lookup? 
Does this PR covers this use case?
I want to find teams whose lead first name was 'Alice' at `ts`.


```
class Employee(AbstractUser):
    ...
simple_history.register(Employee)

class Team(models.Model):
    # Do I have to use HistoricForeignKey here?
    lead = HistoricForeignKey(Employee, models.SET_NULL)  
    ...
simple_history.register(Team)

lead = create_employee(first_name='Alice')
team = create_team(lead=lead)
ts = timezone.now()
lead.first_name = 'Bob'
lead.save()
Team.history.as_of(ts).filter(lead__first_name='Alice').count()
```

The above code return 0. I expect it to return 1.
