### ISSUE TITLE
Use exists() instead of count() in populate_history command

### ISSUE THREAD

**Issue by fabiocapsouza** [jazzband/django-simple-history#922]
**Problem Statement**
The `populate_history` commands take a long time to run when history tables have many rows, mainly because of the `count()` query  that checks if the history already exists:

https://github.com/jazzband/django-simple-history/blob/0f5e15973be68cd40186ac3aebd01d9b620a8e29/simple_history/management/commands/populate_history.py#L159

**Describe the solution you'd like**
I am wondering if the `count()` query could be changed to `exists()` instead. Since the count is only used to check if it returns a truthy value, I believe exists would be a better fit and faster to run. If that is ok, I am happy to send a PR.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jeking3** [comment]
Sounds reasonable to me.  Is there an existing test that covers this code path?

**Comment by fabiocapsouza** [comment]
I believe so. There is a PopulateHistory TestCase
https://github.com/jazzband/django-simple-history/blob/5dfb2f31b343dceb47f514b001bc5031d686a16a/simple_history/tests/tests/test_commands.py#L37

with a specific test with existing objects:

https://github.com/jazzband/django-simple-history/blob/5dfb2f31b343dceb47f514b001bc5031d686a16a/simple_history/tests/tests/test_commands.py#L120

**Comment by jeking3** [comment]
Feel free to open a pull request to make this change.

**Comment by Greg-Hamel** [comment]
This can probably be closed, it has been released in [3.2.0](https://github.com/jazzband/django-simple-history/releases/tag/3.2.0) through the aforementioned MR.

**Comment by ddabble** [comment]
I agree, closing 🙂
