### ISSUE TITLE
Custom Queryset Manager

### ISSUE THREAD

**Issue by pedrocr83** [jazzband/django-simple-history#931]
Greetings,

Not sure if this is possible but i would like to create a custom manager for the history model queryset.(https://docs.djangoproject.com/en/4.0/topics/db/managers/#custom-managers)

I was unable to find any information on this.

Thank you for the help!
Pedro

**Comment by jeking3** [comment]
There may be something in #866 that will help you.  Look for [HistoricalQuerySet](https://github.com/jazzband/django-simple-history/pull/866/files#diff-4b2bcf1fafd0c47640f253c43a1cb48ac5b9a244a013d704192ec3a33e1dd146R12).

**Comment by pedrocr83** [comment]
hey, thanks for the assistance! will look into it and re-open if needed. Cheers!
