### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by 1ace** [jazzband/django-simple-history#960]
It's been a while since 3.0.0 and [a lot has been done](https://github.com/jazzband/django-simple-history/compare/3.0.0...master). Is it time for 3.1.0/4.0.0?

In my case, I need https://github.com/jazzband/django-simple-history/pull/866, and I'm finding myself installing `git+https://github.com/jazzband/django-simple-history#master` to be able to use it.

**Comment by brendanbrett** [comment]
I am also eagerly awaiting a new release, specifically for #866! I hope the great work done by @jeking3 can be reviewed and incorporated soon.

**Comment by 1ace** [comment]
Pinging @barm who did the last release, and @rossmechanic who did pretty much all the releases before that :slightly_smiling_face:

**Comment by jeking3** [comment]
Thanks for the kind words.  I would really like to see #941 get in as well, which builds on top of #866.  I don't mind attempting to drive a release but I have been waiting for an approval on that one for two months.

**Comment by lazarust** [comment]
Getting #941 and #932 merged in and released would be really great for me! They both have features that I'm really needing.

**Comment by utapyngo** [comment]
Can we release them separately? 
#941 is already in.
#932 has conflicts and broken tests, and the author does not seem to have time to resolve them.

**Comment by lazarust** [comment]
That would be fine with me! I just don't want #932 to be forgotten.

**Comment by utapyngo** [comment]
Pinging @barm who did the last release, and @rossmechanic who did pretty much all the releases before that.

**Comment by barm** [comment]
Hey all, sorry for the radio silence. I should be able to help cut a release this week.

**Comment by lazarust** [comment]
@barm Any update on when you think you'd be able to make that release?

**Comment by jeking3** [comment]
Review and approve, if you could: https://github.com/jazzband/django-simple-history/pull/969

**Comment by jeking3** [comment]
https://github.com/jazzband/django-simple-history/releases/tag/3.1.0

As far as I know, apart from dropping Django 2.2, 3.1, Python 3.6 - this is compatible with 3.0.0.  There was a change around the `as_of` call that now returns a filtered QuerySet instead of a list of results.  The documentation for `as_of` explicitly stated that the return value was an Iterable.  This has not changed.  Both list[] and QuerySet are iterable.  Therefore I tagged this as a pre-release for 3.1.0 and we'll see what happens.  The alternative is to make it a 4.0.0 release.

**Comment by utapyngo** [comment]
When will there be a release to PyPI?

**Comment by jeking3** [comment]
I will re-tag and re-spin the v3.1.0 pre-release after that PR passes and gets merged.  I think we need to remove the v3.1.0 pre-release indicator for them to consider publishing it to pypi, but I'm not sure...

**Comment by jeking3** [comment]
Could someone please approve https://github.com/jazzband/django-simple-history/pull/978

**Comment by jeking3** [comment]
Okay I updated the 3.1.0 tag and made another pre-release.  It fixes both the issues found above.

**Comment by jeking3** [comment]
https://github.com/jazzband/help/issues/283

**Comment by jeking3** [comment]
I'm going to put the tag back on 3.1.0 and spin a 3.1.1 release with these fixes, then the roadies can move it up to pypi.

**Comment by jeking3** [comment]
Note: 3.1.0 and 3.1.1 are now in the roadies' hands to get up to pypi.

**Comment by lazarust** [comment]
Any updates on getting this release onto pypi?
