### ISSUE TITLE
Extend source model's QuerySet manager to Historical model?

### ISSUE THREAD

**Issue by dwasyl** [jazzband/django-simple-history#963]
Getting ahead of myself on this great unreleased feature, but..

Based on the great work added in #866, is it at all possible to extend the object manager from the source model to the `Historical` model? The idea here is that now that `as_of()` returns a `HistoricalQuerySet` most of the filtering I want to do on the historical models is based on filtering I would do on live objects.

Since a custom `ModelManager` or `QuerySetManager` that provides chainable filters would work on historical models, to avoid repeating them again, is there a way to use the same manager on the `HistoricalModel`?

**Comment by tim-schilling** [comment]
@dwasyl can you take a look at #1306 to see if it will solve your concern?

**Comment by dwasyl** [comment]
@tim-schilling it looks like a reasonable approach to the same problem. Only thing I forget is needing (in some cases a lot of) duplicated code to bring the queryset classes over from the live one (but that might be unavoidable). Excited to see something like this!

**Comment by tim-schilling** [comment]
@dwasyl Ah, I think I covered that in the docs:

```python

class QuestionQuerySet(HistoricalQuerySet):
    def question_prefixed(self):
        return self.filter(question__startswith='Question: ')

class HistoryQuestionQuerySet(QuestionQuerySet, HistoricalQuerySet):
    """Redefine QuerySet with base class HistoricalQuerySet"""

class Question(models.Model):
    pub_date = models.DateTimeField('date published')
    history = HistoricalRecords(historical_queryset=HistoryQuestionQuerySet)
    manager = models.Manager.from_queryset(QuestionQuerySet)()
```

**Comment by dwasyl** [comment]
That's what I get for giving it only a quick look!

I wasn't familiar with the `models.Manager.from_queryset()` notation style before either so that's a good tip either way.
