### ISSUE TITLE
Disconnect history for tests

### ISSUE THREAD

**Issue by epicserve** [jazzband/django-simple-history#972]
**Problem Statement**
When running tests, you don't need the `post_save` and `post_delete` signals unless you're testing actual Simple History functionality.

**Describe the solution you'd like**
A documented way to turn off Simple History for all tests and then turn it back on for certain tests.

**Comment by duebbert** [comment]
I don't see it documented anywhere but you can set `SIMPLE_HISTORY_ENABLED = False` in your Django settings for the tests.  

Then both `post_save` and `post_delete` will be skipped. See https://github.com/jazzband/django-simple-history/blob/master/simple_history/models.py#L538

**Comment by ddabble** [comment]
I'm assuming the reply from @duebbert resolves this issue, so closing. Please reopen if that's not the case 🙂
